version: '3'
services: 
    database:
        image: 'postgres:latest'
        environment: 
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: financial_register_db
        volumes: 
            - ./pgdata:/var/lib/postgresql/database
        ports: 
            - "5432:5432"